Repository NUTFes/FinanSu, pull requests merged in 2023-06, with the labels that each got.

#591 協賛企業登録のエスケープ処理
  api/docs/docs.go
  api/externals/controller/sponsor_controller.go
  api/externals/repository/sponsor_repository.go
  view/next-project/src/utils/api/sponsor.ts
Labels: enhancement

#593 activityのstyleがない場合にエラーが出ないようにする
  view/next-project/src/components/sponsoractivities/DetailModal.tsx
  view/next-project/src/components/sponsoractivities/EditModal.tsx
  view/next-project/src/components/sponsoractivities/OpenEditModalButton.tsx
  view/next-project/src/pages/sponsoractivities/index.tsx
Labels: bug

#592 協賛企業エスケープ処理対応リリース
  api/docs/docs.go
  api/externals/controller/sponsor_controller.go
  api/externals/repository/sponsor_repository.go
  view/next-project/src/components/sponsoractivities/DetailModal.tsx
  view/next-project/src/components/sponsoractivities/EditModal.tsx
  view/next-project/src/components/sponsoractivities/OpenEditModalButton.tsx
  view/next-project/src/pages/sponsoractivities/index.tsx
  view/next-project/src/utils/api/sponsor.ts
Labels: release

#595 企業ブース以外もある場合は選択可能に
  view/next-project/src/components/sponsoractivities/EditModal.tsx
  view/next-project/src/components/sponsoractivities/SponsorActivitiesAddModal.tsx
Labels: enhancement

#601 purchaseのdeleteの削除の修正
  api/externals/repository/purchase_order_repository.go
  api/internals/usecase/purchase_order_usecase.go
Labels: enhancement

#597 [add]ユーザの絞り込み機能追加
  view/next-project/src/components/fund_information/AddModal.tsx
  view/next-project/src/components/fund_information/EditModal.tsx
  view/next-project/src/components/sponsoractivities/EditModal.tsx
  view/next-project/src/components/sponsoractivities/SponsorActivitiesAddModal.tsx
Labels: enhancement, frontend

#596 Fix/tanaka/468 fix budgetsmodal
  view/next-project/src/components/budgets/AddModal.tsx
  view/next-project/src/components/budgets/DeleteModal.tsx
  view/next-project/src/components/budgets/EditModal.tsx
  view/next-project/src/components/budgets/OpenAddModalButton.tsx
  view/next-project/src/components/budgets/OpenDeleteModalButton.tsx
  view/next-project/src/components/budgets/OpenEditModalButton.tsx
  view/next-project/src/constants/sources.ts
  view/next-project/src/pages/budgets/index.tsx
Labels: bug

#603 バグ修正リリース
  api/externals/repository/purchase_order_repository.go
  api/internals/usecase/purchase_order_usecase.go
  view/next-project/src/components/budgets/AddModal.tsx
  view/next-project/src/components/budgets/DeleteModal.tsx
  view/next-project/src/components/budgets/EditModal.tsx
  view/next-project/src/components/budgets/OpenAddModalButton.tsx
  view/next-project/src/components/budgets/OpenDeleteModalButton.tsx
  view/next-project/src/components/budgets/OpenEditModalButton.tsx
  view/next-project/src/components/fund_information/AddModal.tsx
  view/next-project/src/components/fund_information/EditModal.tsx
  view/next-project/src/components/sponsoractivities/EditModal.tsx
  view/next-project/src/components/sponsoractivities/SponsorActivitiesAddModal.tsx
  view/next-project/src/constants/sources.ts
  view/next-project/src/pages/budgets/index.tsx
  view/next-project/src/pages/sponsoractivities/index.tsx
Labels: release

#604 協賛活動の合計値のNULL処理を追加
  view/next-project/src/pages/sponsoractivities/index.tsx
Labels: release

#605 [fix]募金ページのチェックボックスの修正
  view/next-project/src/pages/fund_informations/index.tsx
Labels: bug, frontend

#606 [fix]編集モーダルの担当者と所属局の修正
  view/next-project/src/components/fund_information/EditModal.tsx
  view/next-project/src/components/sponsoractivities/EditModal.tsx
Labels: bug, frontend

#608 バグ修正リリース
  view/next-project/src/components/fund_information/EditModal.tsx
  view/next-project/src/components/sponsoractivities/EditModal.tsx
  view/next-project/src/pages/fund_informations/index.tsx
  view/next-project/src/pages/purchaseorders/index.tsx
  view/next-project/src/pages/purchasereports/index.tsx
  view/next-project/src/pages/sponsoractivities/index.tsx
Labels: release

#609 [Fix]チェックボックスの修正
  view/next-project/src/components/fund_information/EditModal.tsx
  view/next-project/src/components/sponsoractivities/EditModal.tsx
  view/next-project/src/pages/purchaseorders/index.tsx
  view/next-project/src/pages/purchasereports/index.tsx
Labels: bug, frontend

#612 財務関係修正リリース
  api/docs/docs.go
  api/externals/controller/fund_information_controller.go
  api/externals/repository/fund_information_repository.go
  api/internals/domain/fund_information.go
  api/internals/usecase/fund_information_usecase.go
  mysql/db/fund_informations.sql
  view/next-project/src/components/fund_information/AddModal.tsx
  view/next-project/src/components/fund_information/EditModal.tsx
  view/next-project/src/components/sponsoractivities/EditModal.tsx
  view/next-project/src/pages/fund_informations/index.tsx
  view/next-project/src/pages/purchaseorders/index.tsx
  view/next-project/src/pages/purchasereports/index.tsx
  view/next-project/src/type/common.ts
  view/next-project/src/utils/api/fundInformations.ts
Labels: release

#614 Feature/kubosaka/613 fund informations fix
  view/next-project/src/components/fund_information/AddModal.tsx
  view/next-project/src/components/fund_information/EditModal.tsx
  view/next-project/src/pages/fund_informations/index.tsx
Labels: enhancement

#618 初期データ変更
  view/next-project/src/components/fund_information/AddModal.tsx
Labels: enhancement

#619 制作局が使いやすくするための仕様追加
  api/docs/docs.go
  api/externals/controller/activity_controller.go
  api/externals/repository/activity_repository.go
  api/internals/domain/activity.go
  api/internals/usecase/activity_usecase.go
  mysql/db/activities.sql
  view/next-project/src/components/sponsoractivities/DetailModal.tsx
  view/next-project/src/components/sponsoractivities/EditModal.tsx
  view/next-project/src/components/sponsoractivities/SponsorActivitiesAddModal.tsx
  view/next-project/src/constants/designers.ts
  view/next-project/src/pages/sponsoractivities/index.tsx
  view/next-project/src/type/common.ts
Labels: enhancement

#620 新機能リリース
  api/docs/docs.go
  api/externals/controller/activity_controller.go
  api/externals/repository/activity_repository.go
  api/internals/domain/activity.go
  api/internals/usecase/activity_usecase.go
  mysql/db/activities.sql
  view/next-project/src/components/fund_information/AddModal.tsx
  view/next-project/src/components/fund_information/EditModal.tsx
  view/next-project/src/components/sponsoractivities/DetailModal.tsx
  view/next-project/src/components/sponsoractivities/EditModal.tsx
  view/next-project/src/components/sponsoractivities/SponsorActivitiesAddModal.tsx
  view/next-project/src/constants/designers.ts
  view/next-project/src/pages/fund_informations/index.tsx
  view/next-project/src/pages/sponsoractivities/index.tsx
  view/next-project/src/type/common.ts
Labels: release

#621 activty関係のsqlを追加
  mysql/feature/activity_query.sql
Labels: release

#624 先生の所属に伴う初期値の修正
  view/next-project/src/components/fund_information/AddModal.tsx
Labels: enhancement

#622 協賛活動ページにcsvダウンロード機能を追加
  view/next-project/src/components/common/Title.tsx
  view/next-project/src/pages/sponsoractivities/index.tsx
  view/next-project/src/utils/createActivityCsv.ts
  view/next-project/src/utils/createCsv.ts
  view/next-project/src/utils/downloadFile.ts
Labels: enhancement, frontend
