Repository NUTFes/FinanSu, pull requests merged in 2023-05, with the labels that each got.

#567 渉外局新機能リリース
  api/docs/docs.go
  api/externals/controller/activity_controller.go
  api/externals/repository/activity_repository.go
  api/internals/domain/activity.go
  api/internals/domain/sponsor_style.go
  api/internals/usecase/activity_usecase.go
  mysql/db/activities.sql
  view/next-project/src/components/common/Textarea/Textarea.tsx
  view/next-project/src/components/sponsoractivities/DetailModal.tsx
  view/next-project/src/components/sponsoractivities/EditModal.tsx
  view/next-project/src/components/sponsoractivities/SponsorActivitiesAddModal.tsx
  view/next-project/src/pages/sponsoractivities/index.tsx
  view/next-project/src/type/common.ts
  view/next-project/src/utils/api/sponsorActivities.ts
Labels: release

#568 [fix] createAtのoptional対策を追加　リリース
  view/next-project/src/components/sponsoractivities/SponsorActivitiesAddModal.tsx
  view/next-project/src/pages/sponsoractivities/index.tsx
  view/next-project/src/type/common.ts
Labels: release

#569 募金ページのチェックボックス周りの修正
  mysql/db/users.sql
  view/next-project/src/pages/fund_informations/index.tsx
Labels: bug

#570 募金、協賛活動ページのスマホ対応
  api/externals/repository/fund_information_repository.go
  api/internals/domain/fund_information.go
  api/internals/usecase/fund_information_usecase.go
  mysql/db/departments.sql
  view/next-project/public/rightArrow.svg
  view/next-project/src/components/common/AddButton/AddButton.tsx
  view/next-project/src/components/common/Card/Card.tsx
  view/next-project/src/components/common/EditButton.tsx
  view/next-project/src/components/common/Header/Header.tsx
  view/next-project/src/components/common/SideNav.tsx
  view/next-project/src/components/fund_information/AddModal.tsx
  view/next-project/src/components/fund_information/DeleteModal.tsx
  view/next-project/src/components/fund_information/EditModal.tsx
  view/next-project/src/components/layout/MainLayout/MainLayout.tsx
  view/next-project/src/components/sponsoractivities/DeleteModal.tsx
  view/next-project/src/components/sponsoractivities/DetailModal.tsx
  view/next-project/src/components/sponsoractivities/EditModal.tsx
  view/next-project/src/components/sponsoractivities/OpenAddModalButton.tsx
  view/next-project/src/components/sponsoractivities/SponsorActivitiesAddModal.tsx
  view/next-project/src/pages/fund_informations/index.tsx
  view/next-project/src/pages/sponsoractivities/index.tsx
Labels: enhancement

#575 協賛活動のAPIの修正
  api/docs/docs.go
  api/externals/controller/activity_controller.go
  api/externals/controller/activity_style_controller.go
  api/externals/repository/activity_repository.go
  api/externals/repository/activity_style_repository.go
  api/internals/di/di.go
  api/internals/domain/activity.go
  api/internals/domain/activity_style.go
  api/internals/usecase/activity_style_usecase.go
  api/internals/usecase/activity_usecase.go
  api/router/router.go
  mysql/db/activities.sql
Labels: enhancement

#577 activities/detailsに中間テーブルも紐付ける
  api/externals/repository/activity_repository.go
  api/internals/domain/activity.go
  api/internals/usecase/activity_usecase.go
Labels: enhancement

#579 協賛活動に協賛スタイルを複数紐付ける
  view/next-project/package-lock.json
  view/next-project/package.json
  view/next-project/src/components/budgets/DetailModal.tsx
  view/next-project/src/components/budgets/ExpenseAddModal.tsx
  view/next-project/src/components/common/MultiSelect/MultiSelect.tsx
  view/next-project/src/components/common/MultiSelect/index.ts
  view/next-project/src/components/common/PrimaryButton/PrimaryButton.tsx
  view/next-project/src/components/common/index.ts
  view/next-project/src/components/fund_information/AddModal.tsx
  view/next-project/src/components/fund_information/EditModal.tsx
  view/next-project/src/components/purchaseorders/DetailModal.tsx
  view/next-project/src/components/purchaseorders/EditModal.tsx
  view/next-project/src/components/purchaseorders/PurchaseOrderAddModal.tsx
  view/next-project/src/components/purchasereports/DetailModal.tsx
  view/next-project/src/components/purchasereports/EditModal.tsx
  view/next-project/src/components/purchasereports/PurchaseOrderListModal.tsx
  view/next-project/src/components/purchasereports/PurchaseReportAddModal.tsx
  view/next-project/src/components/purchasereports/PurchaseReportConfirmModal.tsx
  view/next-project/src/components/sponsoractivities/DetailModal.tsx
  view/next-project/src/components/sponsoractivities/EditModal.tsx
  view/next-project/src/components/sponsoractivities/OpenEditModalButton.tsx
  view/next-project/src/components/sponsoractivities/SponsorActivitiesAddModal.tsx
  view/next-project/src/components/sponsors/SponsorAddModal.tsx
  view/next-project/src/components/sponsors/SponsorEditModal.tsx
  view/next-project/src/components/sponsorstyles/SponsorStyleAddModal.tsx
  view/next-project/src/pages/budgets/index.tsx
  view/next-project/src/pages/fund_informations/index.tsx
  view/next-project/src/pages/purchasereports/index.tsx
  view/next-project/src/pages/sponsoractivities/index.tsx
  view/next-project/src/pages/users/index.tsx
  view/next-project/src/type/common.ts
Labels: enhancement

#576 スマホページのテーブルレイアウトの実装
  view/next-project/src/components/auth/SignInView.tsx
  view/next-project/src/components/auth/SignUpView.tsx
  view/next-project/src/components/budgets/ExpenseAddModal.tsx
  view/next-project/src/components/budgets/ExpenseDeleteModal.tsx
  view/next-project/src/components/budgets/ExpenseEditModal.tsx
  view/next-project/src/components/budgets/OpenExpenseAddModalButton.tsx
  view/next-project/src/components/purchaseorders/DeleteModal.tsx
  view/next-project/src/components/purchaseorders/DetailModal.tsx
  view/next-project/src/components/purchaseorders/EditModal.tsx
  view/next-project/src/components/purchaseorders/PurchaseOrderAddModal.tsx
  view/next-project/src/components/purchasereports/AddModal.tsx
  view/next-project/src/components/purchasereports/DeleteModal.tsx
  view/next-project/src/components/purchasereports/DetailModal.tsx
  view/next-project/src/components/purchasereports/EditModal.tsx
  view/next-project/src/components/purchasereports/PurchaseOrderListModal.tsx
  view/next-project/src/components/purchasereports/PurchaseReportAddModal.tsx
  view/next-project/src/components/purchasereports/PurchaseReportItemNumModal.tsx
  view/next-project/src/components/sponsors/DeleteModal.tsx
  view/next-project/src/components/sponsors/SponsorAddModal.tsx
  view/next-project/src/components/sponsors/SponsorEditModal.tsx
  view/next-project/src/components/sponsorstyles/DeleteModal.tsx
  view/next-project/src/components/sponsorstyles/EditModal.tsx
  view/next-project/src/components/sponsorstyles/OpenDeleteModalButton.tsx
  view/next-project/src/components/sponsorstyles/OpenEditModalButton.tsx
  view/next-project/src/components/sponsorstyles/SponsorStyleAddModal.tsx
  view/next-project/src/components/teacher/AddModal.tsx
  view/next-project/src/components/teacher/DeleteModal.tsx
  view/next-project/src/components/teacher/EditModal.tsx
  view/next-project/src/components/users/EditModal.tsx
  view/next-project/src/pages/budgets/index.tsx
  view/next-project/src/pages/index.tsx
  view/next-project/src/pages/purchaseorders/index.tsx
  view/next-project/src/pages/purchasereports/index.tsx
  view/next-project/src/pages/sponsors/index.tsx
  view/next-project/src/pages/sponsorstyles/index.tsx
  view/next-project/src/pages/teachers/index.tsx
Labels: enhancement

#574 デザインを誰が作るのかの選択肢を増やす
  view/next-project/src/components/sponsoractivities/EditModal.tsx
  view/next-project/src/components/sponsoractivities/SponsorActivitiesAddModal.tsx
  view/next-project/src/pages/budgets/index.tsx
Labels: bug

#585 協賛活動追加モーダルが見切れないようにする
  view/next-project/src/components/sponsoractivities/SponsorActivitiesAddModal.tsx
Labels: bug

#584 [fix] 協賛活動の登録時に備考が編集できない問題を解決(#583)
  view/next-project/src/components/sponsoractivities/SponsorActivitiesAddModal.tsx
Labels: bug, frontend

#586 協賛関係修正リリース
  view/next-project/src/components/sponsoractivities/EditModal.tsx
  view/next-project/src/components/sponsoractivities/SponsorActivitiesAddModal.tsx
Labels: release

#588 safariテーブル調整
  view/next-project/src/components/budgets/DetailModal.tsx
  view/next-project/src/pages/purchaseorders/index.tsx
  view/next-project/src/pages/purchasereports/index.tsx
  view/next-project/src/pages/sponsors/index.tsx
Labels: enhancement

#589 safari対応修正
  view/next-project/src/components/budgets/DetailModal.tsx
  view/next-project/src/pages/purchaseorders/index.tsx
  view/next-project/src/pages/purchasereports/index.tsx
  view/next-project/src/pages/sponsors/index.tsx
Labels: release
