Repository NUTFes/FinanSu, pull requests merged in 2023-04, with the labels that each got.

#519 自動リリース機能と自動ラベリング機能の実装
  .github/workflows/auto-labeling.yml
  .github/workflows/auto-release.yml
  .github/workflows/release.yml
  test.yml
Labels: enhancement

#522 購入報告一覧ページの isDisabled のスタイルが正常に当たらない問題を解決
  view/next-project/src/components/fund_information/DisabledDeleteModalButton.tsx
  view/next-project/src/components/fund_information/DisabledEditModalButton.tsx
  view/next-project/src/components/fund_information/OpenDeleteModalButton.tsx
  view/next-project/src/components/fund_information/OpenEditModalButton.tsx
  view/next-project/src/pages/fund_informations/index.tsx
  view/next-project/src/pages/purchaseorders/index.tsx
  view/next-project/src/pages/purchasereports/index.tsx
  view/next-project/src/utils/api/currentUser.ts
Labels: bug, frontend

#524 expenseAPIの修正
  api/internals/usecase/expense_usecase.go
  mysql/db/expense.sql
Labels: bug

#515 bindでデータ取得
  api/docs/docs.go
  api/externals/controller/sponsor_style_controller.go
  api/externals/repository/sponsor_style_repository.go
  api/internals/usecase/sponsor_style_usecase.go
  view/next-project/src/components/sponsorstyles/EditModal.tsx
  view/next-project/src/components/sponsorstyles/SponsorStyleAddModal.tsx
  view/next-project/src/utils/api/api_methods.ts
  view/next-project/src/utils/api/sponsorStyle.ts
Labels: enhancement

#527 支出テーブルの作成
  view/next-project/src/components/budgets/DeleteModal.tsx
  view/next-project/src/components/budgets/DetailModal.tsx
  view/next-project/src/components/budgets/EditModal.tsx
  view/next-project/src/components/sponsoractivities/DetailModal.tsx
  view/next-project/src/pages/budgets/index.tsx
  view/next-project/src/pages/fund_informations/index.tsx
  view/next-project/src/pages/purchaseorders/index.tsx
  view/next-project/src/pages/purchasereports/index.tsx
  view/next-project/src/pages/sponsoractivities/index.tsx
  view/next-project/src/pages/sponsors/index.tsx
  view/next-project/src/pages/sponsorstyles/index.tsx
  view/next-project/src/type/common.ts
  view/next-project/src/utils/api/budget.ts
Labels: enhancement

#529 教員一覧ページのリプレイス
  view/next-project/src/components/common/SideNav.tsx
  view/next-project/src/components/teacher/AddModal.tsx
  view/next-project/src/components/teacher/DeleteModal.tsx
  view/next-project/src/components/teacher/DetailModal.tsx
  view/next-project/src/components/teacher/EditModal.tsx
  view/next-project/src/components/teacher/OpenAddModalButton.tsx
  view/next-project/src/components/teacher/OpenDeleteModalButton.tsx
  view/next-project/src/components/teacher/OpenEditModalButton.tsx
  view/next-project/src/constants/departments.ts
  view/next-project/src/constants/linkItem.tsx
  view/next-project/src/pages/fund_informations/index.tsx
  view/next-project/src/pages/teachers/index.tsx
Labels: bug

#531 不使用モーダルの削除とactions追加
  .github/workflows/auto-build.yml
  .vscode/setting.json
  .vscode/settings.json
  view/next-project/.eslintrc.json
  view/next-project/src/components/auth/SignInView.tsx
  view/next-project/src/components/auth/SignUpView.tsx
  view/next-project/src/components/budgets/DetailModal.tsx
  view/next-project/src/components/budgets/EditModal.tsx
  view/next-project/src/components/common/BureauLabel/BureauLabel.tsx
  view/next-project/src/components/common/Header/Header.tsx
  view/next-project/src/components/common/Label/Label.tsx
  view/next-project/src/components/common/OpenModalButton.tsx
  view/next-project/src/components/fund_information/AddModal.tsx
  view/next-project/src/components/fund_information/EditModal.tsx
  view/next-project/src/components/fund_information/OpenAddModalButton.tsx
  view/next-project/src/components/fund_information/OpenDeleteModalButton.tsx
  view/next-project/src/components/fund_information/OpenEditModalButton.tsx
  view/next-project/src/components/layout/Layout/Layout.tsx
  view/next-project/src/components/layout/MainLayout/MainLayout.tsx
  view/next-project/src/components/purchaseorders/DeleteModal.tsx
  view/next-project/src/components/purchaseorders/EditModal.tsx
  view/next-project/src/components/purchaseorders/OpenAddModalButton.tsx
  view/next-project/src/components/purchaseorders/OpenDeleteModalButton.tsx
  view/next-project/src/components/purchasereports/DeleteModal.tsx
  view/next-project/src/components/purchasereports/PurchaseOrderListModal.tsx
  view/next-project/src/components/sponsoractivities/OpenDeleteModalButton.tsx
  view/next-project/src/components/sponsoractivities/OpenEditModalButton.tsx
  view/next-project/src/components/sponsoractivities/SponsorActivitiesAddModal.tsx
  view/next-project/src/components/sponsors/OpenDeleteModalButton.tsx
  view/next-project/src/components/sponsors/OpenEditModalButton.tsx
  view/next-project/src/components/sponsorstyles/OpenAddModalButton.tsx
  view/next-project/src/components/sponsorstyles/OpenDeleteModalButton.tsx
  view/next-project/src/components/teacher/AddModal.tsx
  view/next-project/src/components/teacher/DeleteModal.tsx
  view/next-project/src/components/teacher/EditModal.tsx
  view/next-project/src/components/teacher/OpenAddModalButton.tsx
  view/next-project/src/components/teacher/OpenDeleteModalButton.tsx
  view/next-project/src/components/teacher/OpenEditModalButton.tsx
  view/next-project/src/constants/linkItem.tsx
  view/next-project/src/index.js
  view/next-project/src/pages/_app.tsx
  view/next-project/src/pages/budgets/index.tsx
  view/next-project/src/pages/fund_informations/index.tsx
  view/next-project/src/pages/purchaseorders/index.tsx
  view/next-project/src/pages/purchasereports/index.tsx
  view/next-project/src/pages/sponsoractivities/index.tsx
  view/next-project/src/pages/sponsors/index.tsx
  view/next-project/src/pages/sponsorstyles/index.tsx
  view/next-project/src/pages/teachers/index.tsx
  view/next-project/src/type/common.ts
  view/next-project/src/utils/api/budget.ts
Labels: bug

#526 usersページのリプレイス
  view/next-project/src/components/users/DeleteModal.tsx
  view/next-project/src/components/users/EditModal.tsx
  view/next-project/src/components/users/OpenDeleteModalButton.tsx
  view/next-project/src/components/users/OpenEditModalButton.tsx
  view/next-project/src/constants/role.ts
  view/next-project/src/pages/users/index.tsx
Labels: bug

#533 usersページ実装リリース
  view/next-project/src/components/users/DeleteModal.tsx
  view/next-project/src/components/users/EditModal.tsx
  view/next-project/src/components/users/OpenDeleteModalButton.tsx
  view/next-project/src/components/users/OpenEditModalButton.tsx
  view/next-project/src/constants/role.ts
  view/next-project/src/pages/users/index.tsx
Labels: release

#534 [fix] import順修正
  view/next-project/src/components/users/EditModal.tsx
  view/next-project/src/components/users/OpenEditModalButton.tsx
Labels: release

#537 本番環境のDockerfileの作成
  api/dev.Dockerfile
  api/prod.Dockerfile
  docker-compose.prod.yml
  docker-compose.yml
Labels: enhancement

#538 [mod] cloudflare config (#505)
  web/prod/config.yml
Labels: bug

#540 インフラ・APIエラーの修正リリース
  api/dev.Dockerfile
  api/docs/docs.go
  api/externals/controller/sponsor_style_controller.go
  api/externals/repository/sponsor_style_repository.go
  api/internals/domain/sponsor_style.go
  api/internals/domain/value_object.go
  api/internals/usecase/activity_usecase.go
  api/internals/usecase/sponsor_style_usecase.go
  api/prod.Dockerfile
  docker-compose.prod.yml
  docker-compose.yml
  finansu-ER.drawio
  mysql/db/sponsor_styles.sql
  view/next-project/src/components/sponsoractivities/DetailModal.tsx
  view/next-project/src/components/sponsoractivities/EditModal.tsx
  view/next-project/src/components/sponsoractivities/SponsorActivitiesAddModal.tsx
  view/next-project/src/components/sponsorstyles/EditModal.tsx
  view/next-project/src/components/sponsorstyles/SponsorStyleAddModal.tsx
  view/next-project/src/constants/scale.ts
  view/next-project/src/pages/sponsoractivities/index.tsx
  view/next-project/src/pages/sponsorstyles/index.tsx
  view/next-project/src/type/common.ts
  web/prod/config.yml
Labels: release

#542 compose.prod修正
  docker-compose.prod.yml
Labels: enhancement

#543 api起動コマンド修正リリース
  docker-compose.prod.yml
Labels: release

#539 全部乗せDockerfileの作成
  prod.api.Dockerfile
  prod.view.Dockerfile
Labels: enhancement

#547 間違えてpushしたものを削除
  view/next-project/src/components/budgets/ExpenseAddModal.tsx
  view/next-project/src/components/budgets/ExpenseDeleteModal.tsx
  view/next-project/src/components/budgets/ExpenseEditModal.tsx
  view/next-project/src/components/budgets/OpenExpenseAddModalButton.tsx
  view/next-project/src/components/budgets/OpenExpenseDeleteModalButton.tsx
  view/next-project/src/components/budgets/OpenExpenseEditModalButton.tsx
  view/next-project/src/components/common/AddButton/AddButton.tsx
  view/next-project/src/components/common/DeleteButton.tsx
  view/next-project/src/components/common/EditButton.tsx
  view/next-project/src/components/sponsoractivities/OpenDeleteModalButton.tsx
  view/next-project/src/components/sponsoractivities/OpenEditModalButton.tsx
  view/next-project/src/pages/budgets/index.tsx
  view/next-project/src/pages/purchaseorders/index.tsx
  view/next-project/src/pages/purchasereports/index.tsx
  view/next-project/src/pages/sponsoractivities/index.tsx
  view/next-project/src/utils/api/budget.ts
Labels: bug

#548 expenseを登録・削除・編集できるようにする+その他バグ修正
  view/next-project/src/components/budgets/ExpenseAddModal.tsx
  view/next-project/src/components/budgets/ExpenseDeleteModal.tsx
  view/next-project/src/components/budgets/ExpenseEditModal.tsx
  view/next-project/src/components/budgets/OpenExpenseAddModalButton.tsx
  view/next-project/src/components/budgets/OpenExpenseDeleteModalButton.tsx
  view/next-project/src/components/budgets/OpenExpenseEditModalButton.tsx
  view/next-project/src/components/common/AddButton/AddButton.tsx
  view/next-project/src/components/common/DeleteButton.tsx
  view/next-project/src/components/common/EditButton.tsx
  view/next-project/src/components/sponsoractivities/OpenDeleteModalButton.tsx
  view/next-project/src/components/sponsoractivities/OpenEditModalButton.tsx
  view/next-project/src/pages/budgets/index.tsx
  view/next-project/src/pages/purchaseorders/index.tsx
  view/next-project/src/pages/purchasereports/index.tsx
  view/next-project/src/pages/sponsoractivities/index.tsx
  view/next-project/src/utils/api/budget.ts
Labels: bug, enhancement

#550 Feature/kubosaka/auto docker hub push
  .github/workflows/auto-DockerHub-push.yml
  prod.view.Dockerfile
Labels: enhancement

#549 データがなくても正常に表示されるようにする
  view/next-project/src/components/layout/Layout/Layout.tsx
  view/next-project/src/components/purchasereports/PurchaseOrderListModal.tsx
  view/next-project/src/components/sponsoractivities/OpenAddModalButton.tsx
  view/next-project/src/components/sponsoractivities/SponsorActivitiesAddModal.tsx
  view/next-project/src/components/sponsors/OpenDeleteModalButton.tsx
  view/next-project/src/components/sponsors/OpenEditModalButton.tsx
  view/next-project/src/components/ui/context.tsx
  view/next-project/src/pages/purchaseorders/index.tsx
  view/next-project/src/pages/purchasereports/index.tsx
  view/next-project/src/pages/sponsoractivities/index.tsx
  view/next-project/src/pages/sponsors/index.tsx
Labels: bug

#553 データがない時の対応リリース
  .github/workflows/auto-DockerHub-push.yml
  prod.api.Dockerfile
  prod.view.Dockerfile
  view/next-project/src/components/budgets/ExpenseAddModal.tsx
  view/next-project/src/components/budgets/ExpenseDeleteModal.tsx
  view/next-project/src/components/budgets/ExpenseEditModal.tsx
  view/next-project/src/components/budgets/OpenExpenseAddModalButton.tsx
  view/next-project/src/components/budgets/OpenExpenseDeleteModalButton.tsx
  view/next-project/src/components/budgets/OpenExpenseEditModalButton.tsx
  view/next-project/src/components/common/AddButton/AddButton.tsx
  view/next-project/src/components/common/DeleteButton.tsx
  view/next-project/src/components/common/EditButton.tsx
  view/next-project/src/components/layout/Layout/Layout.tsx
  view/next-project/src/components/purchasereports/PurchaseOrderListModal.tsx
  view/next-project/src/components/sponsoractivities/OpenAddModalButton.tsx
  view/next-project/src/components/sponsoractivities/OpenDeleteModalButton.tsx
  view/next-project/src/components/sponsoractivities/OpenEditModalButton.tsx
  view/next-project/src/components/sponsoractivities/SponsorActivitiesAddModal.tsx
  view/next-project/src/components/sponsors/OpenDeleteModalButton.tsx
  view/next-project/src/components/sponsors/OpenEditModalButton.tsx
  view/next-project/src/components/ui/context.tsx
  view/next-project/src/pages/budgets/index.tsx
  view/next-project/src/pages/purchaseorders/index.tsx
  view/next-project/src/pages/purchasereports/index.tsx
  view/next-project/src/pages/sponsoractivities/index.tsx
  view/next-project/src/pages/sponsors/index.tsx
  view/next-project/src/utils/api/budget.ts
Labels: release

#554 expense-procedure-fix
  mysql/db/expense.sql
Labels: enhancement

#561 seedデータ変更
  mysql/db/mail_auth.sql
Labels: enhancement

#557 年(年度)指定の追加
  view/next-project/src/pages/budgets/index.tsx
  view/next-project/src/pages/fund_informations/index.tsx
  view/next-project/src/pages/purchaseorders/index.tsx
  view/next-project/src/pages/purchasereports/index.tsx
  view/next-project/src/pages/sponsoractivities/index.tsx
  view/next-project/src/pages/sponsors/index.tsx
  view/next-project/src/pages/sponsorstyles/index.tsx
Labels: enhancement, frontend

#563 年度指定リリース
  mysql/db/expense.sql
  mysql/db/mail_auth.sql
  view/next-project/src/pages/budgets/index.tsx
  view/next-project/src/pages/fund_informations/index.tsx
  view/next-project/src/pages/purchaseorders/index.tsx
  view/next-project/src/pages/purchasereports/index.tsx
  view/next-project/src/pages/sponsoractivities/index.tsx
  view/next-project/src/pages/sponsors/index.tsx
  view/next-project/src/pages/sponsorstyles/index.tsx
Labels: release
