Repository NUTFes/FinanSu, pull requests merged in 2024-03, with the labels that each got.

#684 [feat]募金ページの年度切り替え機能実装
  view/next-project/src/pages/fund_informations/index.tsx
Labels: frontend

#688 [feat] 年度別に取得するAPIを使って表示させるように変更
  view/next-project/src/pages/sponsors/index.tsx
Labels: enhancement, frontend

#691 [fix]expensesのテーブル名変更
  api/externals/repository/expense_repository.go
  mysql/db/expenses.sql
  mysql/feature/add_procedure.sql
Labels: bug

#687 [fix] 各年度ごとに取得するように修正
  view/next-project/src/pages/sponsoractivities/index.tsx
Labels: bug

#699 [fix]購入申請のバグ修正
  view/next-project/src/components/purchaseorders/PurchaseItemNumModal.tsx
  view/next-project/src/components/purchaseorders/PurchaseOrderAddModal.tsx
Labels: frontend

#693 [fix]列名削除、調整
  view/next-project/src/components/purchasereports/PurchaseOrderListModal.tsx
  view/next-project/src/pages/purchasereports/index.tsx
Labels: bug, frontend

#662 [fix]編集モーダルでユーザーが反映されないバグ修正
  view/next-project/src/components/sponsoractivities/EditModal.tsx
Labels: bug

#695 [fix]列名削除、調整
  view/next-project/src/pages/purchaseorders/index.tsx
Labels: bug, frontend

#703 [feat] purchaseItemが無い場合の表示を追加
  view/next-project/src/components/purchaseorders/EditModal.tsx
  view/next-project/src/utils/createPurchaseOrderPdf.ts
Labels: bug

#696 [fix] 登録されたデータが編集モーダルに反映されるよう修正
  view/next-project/src/components/fund_information/EditModal.tsx
Labels: bug

#697 [fix] 企業名確認のためのチェックボックスを追記
  view/next-project/src/components/sponsors/SponsorAddModal.tsx
  view/next-project/src/components/sponsors/SponsorEditModal.tsx
Labels: bug, frontend

#707 [fix] 募金登録モーダルを現在ログインしているユーザー情報に変更
  .gitignore
  view/next-project/src/components/common/Select/Select.tsx
  view/next-project/src/components/fund_information/AddModal.tsx
  view/next-project/src/components/fund_information/OpenAddModalButton.tsx
  view/next-project/src/pages/fund_informations/index.tsx
Labels: frontend

#709 [feat]協賛活動の領収書のPDF出力
  view/next-project/src/components/sponsoractivities/DetailModal.tsx
  view/next-project/src/components/sponsoractivities/OpenPaymentDayModalButton.tsx
  view/next-project/src/components/sponsoractivities/PaymentDayModal.tsx
  view/next-project/src/utils/createSponsorActivityPdf.ts
Labels: enhancement, frontend
