Repository NUTFes/FinanSu, pull requests merged in 2024-04, with the labels that each got.

#710 [fix] 年度別に支出の選択欄を選べるように変更
  api/docs/docs.go
  api/externals/controller/expense_controller.go
  api/internals/domain/expense.go
  api/internals/usecase/expense_usecase.go
  api/router/router.go
  view/next-project/src/components/purchaseorders/OpenAddModalButton.tsx
  view/next-project/src/components/purchaseorders/PurchaseItemNumModal.tsx
  view/next-project/src/pages/purchaseorders/index.tsx
  view/next-project/src/type/common.ts
Labels: bug

#718 協賛活動の2024年度の修正
  api/docs/docs.go
  api/router/router.go
  view/next-project/src/components/sponsoractivities/EditModal.tsx
  view/next-project/src/components/sponsoractivities/OpenAddModalButton.tsx
  view/next-project/src/components/sponsoractivities/OpenEditModalButton.tsx
  view/next-project/src/components/sponsoractivities/SponsorActivitiesAddModal.tsx
  view/next-project/src/pages/sponsoractivities/index.tsx
  view/next-project/src/pages/sponsors/index.tsx
Labels: bug

#720 申請登録の購入したい局を年度別で選択できるように修正
  api/internals/domain/expense.go
  view/next-project/src/components/purchaseorders/OpenAddModalButton.tsx
  view/next-project/src/components/purchaseorders/PurchaseItemNumModal.tsx
  view/next-project/src/pages/purchaseorders/index.tsx
Labels: frontend

#721 予算ページの支出元追加
  view/next-project/src/components/budgets/ExpenditureAddModal.tsx
  view/next-project/src/components/budgets/OpenExpenditureAddModalButton.tsx
  view/next-project/src/pages/budgets/index.tsx
  view/next-project/src/utils/api/budget.ts
Labels: frontend

#723 [feat]購入報告登録のバグ修正
  view/next-project/src/components/purchasereports/PurchaseReportAddModal.tsx
  view/next-project/src/components/purchasereports/PurchaseReportItemNumModal.tsx
Labels: bug, frontend

#734 Fix/yama/733/set default data
  view/next-project/src/components/sponsoractivities/AddPdfDetailModal.tsx
  view/next-project/src/utils/createSponsoractivitiesReceiptPDF.tsx
Labels: bug
