Repository NUTFes/FinanSu, pull requests merged in 2024-05, with the labels that each got.

#685 パスワードリセット用のAPI作成
  api/docs/docs.go
  api/externals/controller/mail_auth_controller.go
  api/externals/controller/password_reset_token_controller.go
  api/externals/repository/mail_auth_repository.go
  api/externals/repository/password_reset_tokens.go
  api/externals/repository/user_repository.go
  api/internals/di/di.go
  api/internals/domain/password_reset_tokens.go
  api/internals/domain/user.go
  api/internals/usecase/mail_auth_usecase.go
  api/internals/usecase/password_reset_token_usecase.go
  api/router/router.go
  docker-compose.prod.yml
  docker-compose.yml
  mysql/db/password_reset_tokens.sql
Labels: backend

#751 物材と生物の物質生物の統合対応
  api/externals/repository/teacher_repository.go
  mysql/db/departments.sql
  mysql/db/teachers_seed.sql
  view/next-project/src/components/fund_information/EditModal.tsx
  view/next-project/src/components/teacher/AddModal.tsx
  view/next-project/src/components/teacher/EditModal.tsx
  view/next-project/src/components/teacher/OpenAddModalButton.tsx
  view/next-project/src/components/teacher/OpenEditModalButton.tsx
  view/next-project/src/constants/departments.ts
  view/next-project/src/pages/fund_informations/index.tsx
  view/next-project/src/pages/teachers/index.tsx
Labels: bug, frontend

#764 [fix]README更新
  README.md
Labels: bug
