Repository NUTFes/FinanSu, pull requests merged in 2024-02, with the labels that each got.

#669 [feat] 年度別のfund_informationsを取得するAPIの作成
  api/docs/docs.go
  api/externals/controller/fund_information_controller.go
  api/externals/repository/fund_information_repository.go
  api/internals/usecase/fund_information_usecase.go
  api/router/router.go
Labels: backend

#674 [feat] 年度別に協賛活動を取得するAPIの作成
  api/docs/docs.go
  api/externals/controller/activity_controller.go
  api/externals/repository/activity_repository.go
  api/internals/usecase/activity_usecase.go
  api/router/router.go
Labels: backend

#679 [feat] 年度で指定されたsponsorsを取得する
  api/docs/docs.go
  api/externals/controller/sponsor_controller.go
  api/externals/repository/sponsor_repository.go
  api/internals/usecase/sponsor_usecase.go
  api/router/router.go
Labels: backend

#683 [fix] 各年度毎に取得するように修正
  view/next-project/src/pages/purchasereports/index.tsx
Labels: bug, frontend

#681 [feat]予算支出ページの年度切り替え実装
  api/docs/docs.go
  api/externals/controller/budget_controller.go
  api/externals/repository/budget_repository.go
  api/internals/usecase/budget_usecase.go
  api/router/router.go
  view/next-project/src/pages/budgets/index.tsx
Labels: frontend
