Repository NUTFes/FinanSu, pull requests merged in 2024-07, with the labels that each got.

#775 教員の論理削除を追加
  api/dev.Dockerfile
  api/docs/docs.go
  api/externals/controller/teacher_controller.go
  api/externals/repository/teacher_repository.go
  api/internals/domain/teacher.go
  api/internals/usecase/fund_information_usecase.go
  api/internals/usecase/teacher_usecase.go
  api/router/router.go
  mysql/db/teachers.sql
  view/next-project/src/components/teacher/DeleteModal.tsx
  view/next-project/src/components/teacher/OpenDeleteModalButton.tsx
  view/next-project/src/components/users/DeleteModal.tsx
  view/next-project/src/pages/teachers/index.tsx
  view/next-project/src/type/common.ts
  view/next-project/src/utils/api/api_methods.ts
  view/next-project/src/utils/api/user.ts
Labels: backend

#816 Makeファイルにコマンド追加
  Makefile
Labels: enhancement

#812 [feat]フィルタありのactivitesのAPI実装
  api/docs/docs.go
  api/externals/controller/activity_controller.go
  api/externals/repository/activity_repository.go
  api/internals/usecase/activity_usecase.go
  api/router/router.go
Labels: backend

#822 APIがDBとの接続できない問題の解消
  Makefile
  docker-compose.db.yml
  docker-compose.local-prod.yml
  docker-compose.yml
  view/local-prod.Dockerfile
Labels: bug

#818 [feat] 年度別で募金登録済みの教員Idを配列で返すAPIの作成
  api/docs/docs.go
  api/externals/controller/teacher_controller.go
  api/externals/repository/teacher_repository.go
  api/internals/usecase/teacher_usecase.go
  api/router/router.go
Labels: enhancement, backend

#825 企業協賛フィルターモーダルの作成
  Makefile
  api/docs/docs.go
  api/externals/controller/activity_controller.go
  api/externals/repository/activity_repository.go
  view/next-project/.eslintrc.json
  view/next-project/src/components/common/Input/Input.module.css
  view/next-project/src/components/common/Modal.tsx
  view/next-project/src/components/common/Select/Select.module.css
  view/next-project/src/components/sponsoractivities/FilterModal.tsx
  view/next-project/src/components/sponsoractivities/OpenAddModalButton.tsx
  view/next-project/src/components/sponsoractivities/index.ts
  view/next-project/src/pages/sponsoractivities/index.tsx
  view/next-project/src/stories/purchaseorders/DetailModal.stories.tsx
  view/next-project/src/stories/purchaseorders/EditModal.stories.tsx
  view/next-project/src/stories/purchaseorders/PurchaseOrderAddModal.stories.tsx
  view/next-project/src/type/common.ts
  view/next-project/src/utils/api/sponsorActivities.ts
  view/next-project/tsconfig.json
  view/next-project/tsconfig.stories.json
Labels: frontend

#833 協賛企業のモーダルを閉じる
  view/next-project/src/components/common/Modal.tsx
  view/next-project/src/components/sponsors/DeleteModal.tsx
  view/next-project/src/components/sponsors/SponsorAddModal.tsx
  view/next-project/src/components/sponsors/SponsorEditModal.tsx
Labels: enhancement

#838 学内募金の登録・編集時に登録済の教員を選択できないようにする
  view/next-project/src/components/fund_information/AddModal.tsx
  view/next-project/src/components/fund_information/EditModal.tsx
  view/next-project/src/components/fund_information/OpenAddModalButton.tsx
  view/next-project/src/components/fund_information/OpenEditModalButton.tsx
  view/next-project/src/pages/fund_informations/index.tsx
Labels: frontend

#843 購入報告のレシート登録用のAPI作成
  api/docs/docs.go
  api/externals/controller/receipt_controller.go
  api/externals/repository/receipt_repository.go
  api/internals/di/di.go
  api/internals/domain/receipt.go
  api/internals/usecase/receipt_usecase.go
  api/router/router.go
  mysql/db/receipts.sql
Labels: backend

#851 sponsorStylesの削除方法を論理削除に変更した
  api/docs/docs.go
  api/externals/repository/sponsor_style_repository.go
  api/internals/domain/sponsor_style.go
  api/internals/usecase/activity_usecase.go
  api/internals/usecase/sponsor_style_usecase.go
  mysql/db/sponsor_styles.sql
Labels: backend

#864 propsの型修正
  view/next-project/src/stories/sponsoractivities/UploadFileModal.stories.tsx
Labels: bug
