Repository NUTFes/FinanSu, pull requests merged in 2025-02, with the labels that each got.

#915 [マイページ]部門予算・詳細取得
  api/externals/controller/festival_item_controller.go
  api/externals/repository/festival_item_repository.go
  api/generated/openapi_gen.go
  api/internals/domain/festival_item.go
  api/internals/usecase/festival_item_usecase.go
  api/router/router.go
  openapi/openapi.yaml
  view/next-project/src/generated/hooks.ts
  view/next-project/src/generated/model/index.ts
Labels: backend

#916 [マイページ]購入報告作成・更新・削除APIの実装
  api/externals/controller/buy_report_controller.go
  api/externals/repository/abstract/abstract_repository.go
  api/externals/repository/buy_report_repository.go
  api/externals/repository/festival_item_repository.go
  api/externals/repository/object_upload_repository.go
  api/externals/repository/transaction_repository.go
  api/internals/di/di.go
  api/internals/domain/buy_report.go
  api/internals/domain/file_information.go
  api/internals/domain/payment_receipt.go
  api/internals/usecase/buy_report_usecase.go
  api/internals/usecase/festival_item_usecase.go
  api/internals/usecase/object_upload_usecase.go
  api/router/router.go
  mysql/db/03_financial_records.sql
  mysql/db/04_divisions.sql
  mysql/db/05_festival_items.sql
  mysql/db/06_item_budgets.sql
  mysql/db/07_user_groups.sql
  mysql/db/08_buy_reports.sql
  mysql/db/09_payment_receipts.sql
  mysql/db/10_buy_statuses.sql
Labels: backend

#881 csvで協賛企業のアップロードを行うAPIの作成＆返り値取得のためrowAffeted件数分の取得を作成
  api/externals/controller/sponsor_controller.go
  api/externals/repository/abstract/abstract_repository.go
  api/externals/repository/sponsor_repository.go
  api/internals/usecase/sponsor_usecase.go
  api/router/router.go
Labels: backend

#922 [マイページ]API繋ぎ込み
  api/internals/usecase/festival_item_usecase.go
  view/next-project/src/components/mypage/Status.tsx
  view/next-project/src/components/mypage/TableSection.tsx
  view/next-project/src/pages/mypage/index.tsx
  view/next-project/src/pages/mypage/mockData.ts
Labels: frontend

#923 購入報告で必要なAPI作成
  api/externals/controller/division_controller.go
  api/externals/controller/festival_item_controller.go
  api/externals/repository/division_repository.go
  api/externals/repository/festival_item_repository.go
  api/generated/openapi_gen.go
  api/internals/usecase/division_usecase.go
  api/internals/usecase/festival_item_usecase.go
  api/router/router.go
  openapi/openapi.yaml
  view/next-project/src/generated/hooks.ts
  view/next-project/src/generated/model/index.ts
Labels: backend

#927 [予算管理]CSVのダウンロードAPI作成
  api/externals/controller/financial_record_controller.go
  api/externals/repository/financial_record_repository.go
  api/generated/openapi_gen.go
  api/internals/domain/financial_record.go
  api/internals/usecase/financial_record_usecase.go
  api/router/router.go
  openapi/openapi.yaml
  view/next-project/src/generated/hooks.ts
  view/next-project/src/generated/model/index.ts
Labels: backend

#930 リリースノートのworkflowのfailの修正
  .github/release.yml
  .github/workflows/auto-release.yml
Labels: bug
