Repository NUTFes/FinanSu, pull requests merged in 2025-03, with the labels that each got.

#932 予算管理ページの実装
  view/next-project/package-lock.json
  view/next-project/package.json
  view/next-project/src/components/budget_managements/AddBudgetManagementModal.tsx
  view/next-project/src/components/budget_managements/BudgetManagement.tsx
  view/next-project/src/components/budget_managements/OpenAddModalButton.tsx
  view/next-project/src/components/common/Formatter.tsx
  view/next-project/src/components/common/Input/Input.tsx
  view/next-project/src/components/common/OutlinePrimaryButton/OutlinePrimaryButton.tsx
  view/next-project/src/constants/linkItem.tsx
  view/next-project/src/generated/model/buyReport.ts
  view/next-project/src/generated/model/buyReportDetail.ts
  view/next-project/src/generated/model/buyReportInformation.ts
  view/next-project/src/generated/model/buyReportInformationStatus.ts
  view/next-project/src/generated/model/deleteBuyReportsId200.ts
  view/next-project/src/generated/model/festivalItemWithReport.ts
  view/next-project/src/generated/model/festivalItemsForMyPage.ts
  view/next-project/src/generated/model/getBuyReportsDetailsParams.ts
  view/next-project/src/generated/model/getDivisionsParams.ts
  view/next-project/src/generated/model/getFestivalItemsDetailsUserIdParams.ts
  view/next-project/src/generated/model/getFestivalItemsParams.ts
  view/next-project/src/generated/model/postBuyReportsBody.ts
  view/next-project/src/generated/model/postUploadFile200.ts
  view/next-project/src/generated/model/postUploadFileBody.ts
  view/next-project/src/generated/model/putBuyReportStatusBuyReportIdBody.ts
  view/next-project/src/generated/model/putBuyReportsIdBody.ts
  view/next-project/src/pages/_app.tsx
  view/next-project/src/pages/budget_managements/index.tsx
Labels: frontend

#938 予算管理編集・削除・csvダウンロード機能作成
  api/externals/controller/division_controller.go
  api/externals/controller/festival_item_controller.go
  api/externals/controller/financial_record_controller.go
  api/externals/repository/division_repository.go
  api/externals/repository/festival_item_repository.go
  api/externals/repository/financial_record_repository.go
  api/generated/openapi_gen.go
  api/internals/usecase/division_usecase.go
  api/internals/usecase/festival_item_usecase.go
  api/internals/usecase/financial_record_usecase.go
  api/router/router.go
  mysql/db/03_financial_records.sql
  mysql/db/04_divisions.sql
  mysql/db/05_festival_items.sql
  mysql/db/06_item_budgets.sql
  mysql/db/07_user_groups.sql
  mysql/db/08_buy_reports.sql
  openapi/openapi.yaml
  view/next-project/src/components/budget_managements/AddBudgetManagementModal.tsx
  view/next-project/src/components/budget_managements/BudgetManagement.tsx
  view/next-project/src/components/budget_managements/DeleteBudgetManagementModal.tsx
  view/next-project/src/components/budget_managements/EditBudgetManagementModal.tsx
  view/next-project/src/components/budget_managements/OpenAddModalButton.tsx
  view/next-project/src/components/budget_managements/OpenDeleteModalButton.tsx
  view/next-project/src/components/budget_managements/OpenEditModalButton.tsx
  view/next-project/src/generated/hooks.ts
  view/next-project/src/generated/model/division.ts
  view/next-project/src/generated/model/festivalItem.ts
  view/next-project/src/generated/model/financialRecord.ts
  view/next-project/src/pages/budget_managements/index.tsx
Labels: frontend

#941 golangciバージョン更新
  .github/workflows/golangci-lint.yml
  .golangci.yml
  api/drivers/db/db.go
  api/externals/controller/activity_controller.go
  api/externals/controller/mail_auth_controller.go
  api/externals/controller/sponsor_controller.go
  api/externals/controller/user_controller.go
  api/externals/repository/mail_auth_repository.go
  api/externals/repository/object_upload_repository.go
  api/externals/repository/user_repository.go
  api/externals/repository/year_repository.go
  api/internals/usecase/activity_information_usecase.go
  api/internals/usecase/activity_style_usecase.go
  api/internals/usecase/activity_usecase.go
  api/internals/usecase/budget_usecase.go
  api/internals/usecase/bureau_usecase.go
  api/internals/usecase/buy_report_usecase.go
  api/internals/usecase/department_usecase.go
  api/internals/usecase/division_usecase.go
  api/internals/usecase/expense_usecase.go
  api/internals/usecase/festival_item_usecase.go
  api/internals/usecase/financial_record_usecase.go
  api/internals/usecase/fund_information_usecase.go
  api/internals/usecase/mail_auth_usecase.go
  api/internals/usecase/password_reset_token_usecase.go
  api/internals/usecase/purchase_item_usecase.go
  api/internals/usecase/purchase_order_usecase.go
  api/internals/usecase/purchase_report_usecase.go
  api/internals/usecase/receipt_usecase.go
  api/internals/usecase/source_usecase.go
  api/internals/usecase/sponsor_style_usecase.go
  api/internals/usecase/sponsor_usecase.go
  api/internals/usecase/teacher_usecase.go
  api/internals/usecase/user_usecase.go
  api/internals/usecase/year_usecase.go
  api/main.go
  api/test/sample_test.go
Labels: bug

#952 [バグ修正]予算管理の局のバグ修正
  api/externals/repository/abstract/abstract_repository.go
  api/externals/repository/financial_record_repository.go
Labels: bug, backend

#954 [バグ修正]マイページのバグ修正
  api/internals/usecase/festival_item_usecase.go
Labels: bug, backend

#957 [バグ修正]CSVダウンロードAPI修正
  api/externals/controller/financial_record_controller.go
  api/externals/repository/financial_record_repository.go
  api/go.mod
  api/go.sum
Labels: bug, backend

#958 golangciのlintエラー対応
  .github/workflows/golangci-lint.yml
  .golangci.yml
  api/internals/usecase/division_usecase.go
Labels: bug, backend

#963 festival_itemsのAPI修正
  .golangci.yml
  api/externals/repository/festival_item_repository.go
Labels: bug, backend
